[project]
name = "chatpdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fitz>=0.0.1.dev2",
    "openai>=1.84.0",
    "pymupdf>=1.26.0",
    "streamlit>=1.45.1",
]
